<template>
    <el-form>
        <el-form>
            <el-form-item>
                <el-input></el-input>
            </el-form-item>
            <el-form-item>
                <el-switch></el-switch>
            </el-form-item>
        </el-form>
    </el-form>
</template>
